enableGlobalCache: false

# httpProxy: "http://127.0.0.1:1081"

# httpsProxy: "http://127.0.0.1:1081"

nodeLinker: node-modules

npmRegistryServer: "https://registry.npm.taobao.org"

yarnPath: .yarn/releases/yarn-2.4.2.cjs
